import type { LeaveRow } from "./types";

// Synthetic demo data (fictional names/IDs) used only when no Google Sheet is
// configured, so the dashboard layout renders out of the box. Real data comes
// live from your connected sheet — see src/lib/config.ts and README.md.
export const SAMPLE_ROWS: LeaveRow[] = [
  {
    "employeeName": "Arjun Patel",
    "mediamintId": "MM3617",
    "email": "arjun.patel@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "RH",
    "daysHours": "3 Days",
    "appliedOn": "2026-07-10 00:00:00",
    "leaveDates": "Jun 24 2026 - Jun 26 2026",
    "reason": "Festival holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending"
  },
  {
    "employeeName": "Vikram Reddy",
    "mediamintId": "MM4078",
    "email": "vikram.reddy@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "PTO",
    "daysHours": "2 Days",
    "appliedOn": "2026-07-10 00:00:00",
    "leaveDates": "Jun 25 2026 - Jun 26 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending"
  },
  {
    "employeeName": "Meera Nair",
    "mediamintId": "MM4257",
    "email": "meera.nair@mediamint.com",
    "managerName": "Suresh Babu",
    "leaveType": "SL",
    "daysHours": "0.5 Day",
    "appliedOn": "2026-06-25 00:00:00",
    "leaveDates": "Jul 26 2026",
    "reason": "Not feeling well",
    "day": "Half",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn"
  },
  {
    "employeeName": "Vikram Reddy",
    "mediamintId": "MM4363",
    "email": "vikram.reddy@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "CL",
    "daysHours": "1 Day",
    "appliedOn": "2026-03-31 00:00:00",
    "leaveDates": "Jun 23 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected"
  },
  {
    "employeeName": "Sara Pillai",
    "mediamintId": "MM2590",
    "email": "sara.pillai@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "CL",
    "daysHours": "1 Day",
    "appliedOn": "2026-06-10 00:00:00",
    "leaveDates": "Jul 26 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Vikram Rao",
    "mediamintId": "MM3525",
    "email": "vikram.rao@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "PTO",
    "daysHours": "3 Days",
    "appliedOn": "2026-02-20 00:00:00",
    "leaveDates": "Jun 24 2026 - Jun 26 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Kabir Joshi",
    "mediamintId": "MM4786",
    "email": "kabir.joshi@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "CL",
    "daysHours": "2 Days",
    "appliedOn": "2026-03-23 00:00:00",
    "leaveDates": "Jul 10 2026 - Jul 11 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Meera Gupta",
    "mediamintId": "MM4863",
    "email": "meera.gupta@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "OT",
    "daysHours": "8 Hours",
    "appliedOn": "2026-06-20 00:00:00",
    "leaveDates": "Jul 26 2026",
    "reason": "Worked on a mandatory holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected"
  },
  {
    "employeeName": "Aryan Bose",
    "mediamintId": "MM4987",
    "email": "aryan.bose@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "SL",
    "daysHours": "1 Day",
    "appliedOn": "2026-04-28 00:00:00",
    "leaveDates": "Jul 28 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected"
  },
  {
    "employeeName": "Ishita Bose",
    "mediamintId": "MM2622",
    "email": "ishita.bose@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "SL",
    "daysHours": "1 Day",
    "appliedOn": "2026-03-25 00:00:00",
    "leaveDates": "Jun 22 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected"
  },
  {
    "employeeName": "Sneha Bose",
    "mediamintId": "MM3393",
    "email": "sneha.bose@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "ML",
    "daysHours": "30 Days",
    "appliedOn": "2026-04-12 00:00:00",
    "leaveDates": "Jul 28 2026 - Aug 27 2026",
    "reason": "Maternity leave",
    "day": "Full",
    "startDate": "Jul 28 2026",
    "endDate": "Aug 27 2026",
    "status": "Rejected"
  },
  {
    "employeeName": "Vivaan Nair",
    "mediamintId": "MM3105",
    "email": "vivaan.nair@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "SL",
    "daysHours": "1 Day",
    "appliedOn": "2026-06-24 00:00:00",
    "leaveDates": "Jun 23 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn"
  },
  {
    "employeeName": "Anjali Verma",
    "mediamintId": "MM3165",
    "email": "anjali.verma@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "PL",
    "daysHours": "2 Days",
    "appliedOn": "2026-04-03 00:00:00",
    "leaveDates": "Jul 12 2026 - Jul 14 2026",
    "reason": "Paternity leave",
    "day": "Full",
    "startDate": "Jul 12 2026",
    "endDate": "Jul 14 2026",
    "status": "Pending"
  },
  {
    "employeeName": "Ishita Bhat",
    "mediamintId": "MM2479",
    "email": "ishita.bhat@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "SL",
    "daysHours": "1 Day",
    "appliedOn": "2026-06-25 00:00:00",
    "leaveDates": "Jul 03 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn"
  },
  {
    "employeeName": "Dev Mehta",
    "mediamintId": "MM4033",
    "email": "dev.mehta@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "PTO",
    "daysHours": "2 Days",
    "appliedOn": "2026-05-29 00:00:00",
    "leaveDates": "Jul 18 2026 - Jul 19 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected"
  },
  {
    "employeeName": "Aryan Patel",
    "mediamintId": "MM3763",
    "email": "aryan.patel@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "CL",
    "daysHours": "2 Days",
    "appliedOn": "2026-04-30 00:00:00",
    "leaveDates": "Jul 16 2026 - Jul 17 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Vivaan Gupta",
    "mediamintId": "MM2619",
    "email": "vivaan.gupta@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "PTO",
    "daysHours": "2 Days",
    "appliedOn": "2026-05-12 00:00:00",
    "leaveDates": "Jun 20 2026 - Jun 21 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected"
  },
  {
    "employeeName": "Rohan Kulkarni",
    "mediamintId": "MM2016",
    "email": "rohan.kulkarni@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "PTO",
    "daysHours": "1 Day",
    "appliedOn": "2026-03-25 00:00:00",
    "leaveDates": "Jul 24 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected"
  },
  {
    "employeeName": "Arjun Patel",
    "mediamintId": "MM4828",
    "email": "arjun.patel@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "CL",
    "daysHours": "3 Days",
    "appliedOn": "2026-06-27 00:00:00",
    "leaveDates": "Jul 19 2026 - Jul 21 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending"
  },
  {
    "employeeName": "Dev Mehta",
    "mediamintId": "MM2424",
    "email": "dev.mehta@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "SL",
    "daysHours": "0.5 Day",
    "appliedOn": "2026-03-30 00:00:00",
    "leaveDates": "Jun 23 2026",
    "reason": "Not feeling well",
    "day": "Half",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending"
  },
  {
    "employeeName": "Ananya Bose",
    "mediamintId": "MM4460",
    "email": "ananya.bose@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "PTO",
    "daysHours": "3 Days",
    "appliedOn": "2026-06-14 00:00:00",
    "leaveDates": "Jun 20 2026 - Jun 22 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Ananya Chopra",
    "mediamintId": "MM4513",
    "email": "ananya.chopra@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "PTO",
    "daysHours": "3 Days",
    "appliedOn": "2026-06-22 00:00:00",
    "leaveDates": "Jul 03 2026 - Jul 05 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending"
  },
  {
    "employeeName": "Sameer Das",
    "mediamintId": "MM3422",
    "email": "sameer.das@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "CL",
    "daysHours": "0.5 Day",
    "appliedOn": "2026-04-08 00:00:00",
    "leaveDates": "Jul 20 2026 - Jul 21 2026",
    "reason": "Personal work",
    "day": "Half",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending"
  },
  {
    "employeeName": "Riya Kulkarni",
    "mediamintId": "MM2351",
    "email": "riya.kulkarni@mediamint.com",
    "managerName": "Suresh Babu",
    "leaveType": "PTO",
    "daysHours": "1 Day",
    "appliedOn": "2026-06-14 00:00:00",
    "leaveDates": "Jul 11 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending"
  },
  {
    "employeeName": "Ishita Kapoor",
    "mediamintId": "MM2094",
    "email": "ishita.kapoor@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "PTO",
    "daysHours": "1 Day",
    "appliedOn": "2026-02-25 00:00:00",
    "leaveDates": "Jul 13 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn"
  },
  {
    "employeeName": "Nisha Sharma",
    "mediamintId": "MM4163",
    "email": "nisha.sharma@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "OT",
    "daysHours": "8 Hours",
    "appliedOn": "2026-06-17 00:00:00",
    "leaveDates": "Jul 06 2026",
    "reason": "Worked on a mandatory holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Manish Menon",
    "mediamintId": "MM4181",
    "email": "manish.menon@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "CL",
    "daysHours": "3 Days",
    "appliedOn": "2026-03-04 00:00:00",
    "leaveDates": "Jul 11 2026 - Jul 13 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Varun Mehta",
    "mediamintId": "MM2928",
    "email": "varun.mehta@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "PTO",
    "daysHours": "1 Day",
    "appliedOn": "2026-02-28 00:00:00",
    "leaveDates": "Jul 21 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn"
  },
  {
    "employeeName": "Aarav Das",
    "mediamintId": "MM3934",
    "email": "aarav.das@mediamint.com",
    "managerName": "Suresh Babu",
    "leaveType": "OT",
    "daysHours": "8 Hours",
    "appliedOn": "2026-05-22 00:00:00",
    "leaveDates": "Jul 28 2026",
    "reason": "Worked on a mandatory holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending"
  },
  {
    "employeeName": "Kavya Chopra",
    "mediamintId": "MM2329",
    "email": "kavya.chopra@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "PTO",
    "daysHours": "2 Days",
    "appliedOn": "2026-06-14 00:00:00",
    "leaveDates": "Jul 04 2026 - Jul 05 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Kabir Joshi",
    "mediamintId": "MM4556",
    "email": "kabir.joshi@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "RH",
    "daysHours": "1 Day",
    "appliedOn": "2026-07-10 00:00:00",
    "leaveDates": "Jul 20 2026",
    "reason": "Festival holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn"
  },
  {
    "employeeName": "Varun Iyer",
    "mediamintId": "MM3591",
    "email": "varun.iyer@mediamint.com",
    "managerName": "Suresh Babu",
    "leaveType": "PL",
    "daysHours": "5 Days",
    "appliedOn": "2026-05-20 00:00:00",
    "leaveDates": "Jul 20 2026 - Jul 25 2026",
    "reason": "Paternity leave",
    "day": "Full",
    "startDate": "Jul 20 2026",
    "endDate": "Jul 25 2026",
    "status": "Pending"
  },
  {
    "employeeName": "Arjun Nair",
    "mediamintId": "MM4956",
    "email": "arjun.nair@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "SL",
    "daysHours": "1 Day",
    "appliedOn": "2026-03-14 00:00:00",
    "leaveDates": "Jul 15 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn"
  },
  {
    "employeeName": "Ishita Patel",
    "mediamintId": "MM2112",
    "email": "ishita.patel@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "PTO",
    "daysHours": "3 Days",
    "appliedOn": "2026-03-13 00:00:00",
    "leaveDates": "Jun 29 2026 - Jul 01 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected"
  },
  {
    "employeeName": "Anjali Chopra",
    "mediamintId": "MM2638",
    "email": "anjali.chopra@mediamint.com",
    "managerName": "Suresh Babu",
    "leaveType": "CL",
    "daysHours": "0.5 Day",
    "appliedOn": "2026-02-20 00:00:00",
    "leaveDates": "Jun 28 2026",
    "reason": "Personal work",
    "day": "Half",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected"
  },
  {
    "employeeName": "Nisha Patel",
    "mediamintId": "MM3776",
    "email": "nisha.patel@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "PTO",
    "daysHours": "1 Day",
    "appliedOn": "2026-05-17 00:00:00",
    "leaveDates": "Jun 21 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Karan Menon",
    "mediamintId": "MM4402",
    "email": "karan.menon@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "OT",
    "daysHours": "8 Hours",
    "appliedOn": "2026-05-05 00:00:00",
    "leaveDates": "Jul 24 2026",
    "reason": "Worked on a mandatory holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Nisha Chopra",
    "mediamintId": "MM3876",
    "email": "nisha.chopra@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "LOP",
    "daysHours": "30 Days",
    "appliedOn": "2026-02-11 00:00:00",
    "leaveDates": "Jul 23 2026 - Aug 22 2026",
    "reason": "Extended personal leave",
    "day": "Full",
    "startDate": "Jul 23 2026",
    "endDate": "Aug 22 2026",
    "status": "Rejected"
  },
  {
    "employeeName": "Neha Patel",
    "mediamintId": "MM4144",
    "email": "neha.patel@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "CL",
    "daysHours": "3 Days",
    "appliedOn": "2026-07-06 00:00:00",
    "leaveDates": "Jul 18 2026 - Jul 20 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Ishita Patel",
    "mediamintId": "MM3939",
    "email": "ishita.patel@mediamint.com",
    "managerName": "Suresh Babu",
    "leaveType": "RH",
    "daysHours": "1 Day",
    "appliedOn": "2026-06-10 00:00:00",
    "leaveDates": "Jul 25 2026",
    "reason": "Festival holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Karan Kapoor",
    "mediamintId": "MM4275",
    "email": "karan.kapoor@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "SL",
    "daysHours": "0.5 Day",
    "appliedOn": "2026-06-13 00:00:00",
    "leaveDates": "Jul 25 2026",
    "reason": "Not feeling well",
    "day": "Half",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved"
  },
  {
    "employeeName": "Manish Iyer",
    "mediamintId": "MM4079",
    "email": "manish.iyer@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "SL",
    "daysHours": "1 Day",
    "appliedOn": "2026-02-17 00:00:00",
    "leaveDates": "Jun 21 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending"
  },
  {
    "employeeName": "Tara Kapoor",
    "mediamintId": "MM4482",
    "email": "tara.kapoor@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "CL",
    "daysHours": "3 Days",
    "appliedOn": "2026-05-20 00:00:00",
    "leaveDates": "Jul 07 2026 - Jul 09 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending"
  },
  {
    "employeeName": "Meera Kapoor",
    "mediamintId": "MM3063",
    "email": "meera.kapoor@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "CL",
    "daysHours": "0.5 Day",
    "appliedOn": "2026-05-20 00:00:00",
    "leaveDates": "Jul 18 2026",
    "reason": "Personal work",
    "day": "Half",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending"
  },
  {
    "employeeName": "Arjun Nair",
    "mediamintId": "MM4749",
    "email": "arjun.nair@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "OT",
    "daysHours": "4 Hours",
    "appliedOn": "2026-03-23 00:00:00",
    "leaveDates": "Jun 24 2026",
    "reason": "Worked on a mandatory holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn"
  },
  {
    "employeeName": "Sneha Iyer",
    "mediamintId": "MM2632",
    "email": "sneha.iyer@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "PL",
    "daysHours": "10 Days",
    "appliedOn": "2026-04-08 00:00:00",
    "leaveDates": "Jun 29 2026 - Jul 09 2026",
    "reason": "Paternity leave",
    "day": "Full",
    "startDate": "Jun 29 2026",
    "endDate": "Jul 09 2026",
    "status": "Approved"
  }
];
