import type { LeaveRow } from "./types";

// Synthetic demo data (fictional names/IDs) used only when no Google Sheet is
// configured, so the dashboard layout renders out of the box. Real data comes
// live from your connected sheet — see src/lib/config.ts and README.md.
export const SAMPLE_ROWS: LeaveRow[] = [
  {
    "employeeName": "Arjun Patel",
    "mediamintId": "MM3617",
    "email": "arjun.patel@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "RH",
    "daysHours": "3 Days",
    "appliedOn": "2026-07-10 00:00:00",
    "leaveDates": "Jun 24 2026 - Jun 26 2026",
    "reason": "Festival holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending",
    "country": "India"
  },
  {
    "employeeName": "Diya Kapoor",
    "mediamintId": "MM2879",
    "email": "diya.kapoor@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "PTO",
    "daysHours": "2 Days",
    "appliedOn": "2026-07-10 00:00:00",
    "leaveDates": "Jul 17 2026 - Jul 18 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending",
    "country": "India"
  },
  {
    "employeeName": "Neha Pillai",
    "mediamintId": "MM2242",
    "email": "neha.pillai@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "CL",
    "daysHours": "3 Days",
    "appliedOn": "2026-06-09 00:00:00",
    "leaveDates": "Jul 04 2026 - Jul 06 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "Philippines"
  },
  {
    "employeeName": "Dev Reddy",
    "mediamintId": "MM2905",
    "email": "dev.reddy@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "PTO",
    "daysHours": "1 Day",
    "appliedOn": "2026-02-18 00:00:00",
    "leaveDates": "Jun 28 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending",
    "country": "India"
  },
  {
    "employeeName": "Ananya Sinha",
    "mediamintId": "MM3263",
    "email": "ananya.sinha@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "CL",
    "daysHours": "1 Day",
    "appliedOn": "2026-05-25 00:00:00",
    "leaveDates": "Jun 26 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Rahul Nair",
    "mediamintId": "MM4311",
    "email": "rahul.nair@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "PTO",
    "daysHours": "3 Days",
    "appliedOn": "2026-05-19 00:00:00",
    "leaveDates": "Jul 21 2026 - Jul 23 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending",
    "country": "India"
  },
  {
    "employeeName": "Vikram Verma",
    "mediamintId": "MM3481",
    "email": "vikram.verma@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "OT",
    "daysHours": "4 Hours",
    "appliedOn": "2026-05-08 00:00:00",
    "leaveDates": "Jul 01 2026",
    "reason": "Worked on a mandatory holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "Philippines"
  },
  {
    "employeeName": "Karan Joshi",
    "mediamintId": "MM3406",
    "email": "karan.joshi@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "PL",
    "daysHours": "90 Days",
    "appliedOn": "2026-03-18 00:00:00",
    "leaveDates": "Jul 08 2026 - Oct 06 2026",
    "reason": "Paternity leave",
    "day": "Full",
    "startDate": "Jul 08 2026",
    "endDate": "Oct 06 2026",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Priya Gupta",
    "mediamintId": "MM3401",
    "email": "priya.gupta@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "PTO",
    "daysHours": "1 Day",
    "appliedOn": "2026-03-07 00:00:00",
    "leaveDates": "Jul 16 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn",
    "country": "India"
  },
  {
    "employeeName": "Vikram Bose",
    "mediamintId": "MM3393",
    "email": "vikram.bose@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "ML",
    "daysHours": "30 Days",
    "appliedOn": "2026-04-12 00:00:00",
    "leaveDates": "Jul 28 2026 - Aug 27 2026",
    "reason": "Maternity leave",
    "day": "Full",
    "startDate": "Jul 28 2026",
    "endDate": "Aug 27 2026",
    "status": "Rejected",
    "country": "United States"
  },
  {
    "employeeName": "Varun Nair",
    "mediamintId": "MM3105",
    "email": "varun.nair@mediamint.com",
    "managerName": "Suresh Babu",
    "leaveType": "SL",
    "daysHours": "1 Day",
    "appliedOn": "2026-06-24 00:00:00",
    "leaveDates": "Jun 23 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn",
    "country": "Philippines"
  },
  {
    "employeeName": "Varun Verma",
    "mediamintId": "MM3165",
    "email": "varun.verma@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "PL",
    "daysHours": "2 Days",
    "appliedOn": "2026-04-03 00:00:00",
    "leaveDates": "Jul 12 2026 - Jul 14 2026",
    "reason": "Paternity leave",
    "day": "Full",
    "startDate": "Jul 12 2026",
    "endDate": "Jul 14 2026",
    "status": "Pending",
    "country": "India"
  },
  {
    "employeeName": "Tara Iyer",
    "mediamintId": "MM4022",
    "email": "tara.iyer@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "PTO",
    "daysHours": "1 Day",
    "appliedOn": "2026-05-16 00:00:00",
    "leaveDates": "Jul 08 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn",
    "country": "India"
  },
  {
    "employeeName": "Dev Joshi",
    "mediamintId": "MM2330",
    "email": "dev.joshi@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "PTO",
    "daysHours": "3 Days",
    "appliedOn": "2026-03-18 00:00:00",
    "leaveDates": "Jul 15 2026 - Jul 17 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Divya Ghosh",
    "mediamintId": "MM3140",
    "email": "divya.ghosh@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "ML",
    "daysHours": "30 Days",
    "appliedOn": "2026-03-26 00:00:00",
    "leaveDates": "Jul 12 2026 - Aug 11 2026",
    "reason": "Maternity leave",
    "day": "Full",
    "startDate": "Jul 12 2026",
    "endDate": "Aug 11 2026",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Ishita Patel",
    "mediamintId": "MM2950",
    "email": "ishita.patel@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "LOP",
    "daysHours": "30 Days",
    "appliedOn": "2026-05-12 00:00:00",
    "leaveDates": "Jun 20 2026 - Jul 20 2026",
    "reason": "Extended personal leave",
    "day": "Full",
    "startDate": "Jun 20 2026",
    "endDate": "Jul 20 2026",
    "status": "Rejected",
    "country": "India"
  },
  {
    "employeeName": "Sara Sharma",
    "mediamintId": "MM2596",
    "email": "sara.sharma@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "SL",
    "daysHours": "1 Day",
    "appliedOn": "2026-02-24 00:00:00",
    "leaveDates": "Jul 13 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "United States"
  },
  {
    "employeeName": "Sameer Reddy",
    "mediamintId": "MM3870",
    "email": "sameer.reddy@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "LOP",
    "daysHours": "30 Days",
    "appliedOn": "2026-02-17 00:00:00",
    "leaveDates": "Jul 15 2026 - Aug 14 2026",
    "reason": "Extended personal leave",
    "day": "Full",
    "startDate": "Jul 15 2026",
    "endDate": "Aug 14 2026",
    "status": "Pending",
    "country": "India"
  },
  {
    "employeeName": "Riya Mehta",
    "mediamintId": "MM2254",
    "email": "riya.mehta@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "PTO",
    "daysHours": "2 Days",
    "appliedOn": "2026-06-23 00:00:00",
    "leaveDates": "Jul 03 2026 - Jul 04 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Tara Reddy",
    "mediamintId": "MM2419",
    "email": "tara.reddy@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "PTO",
    "daysHours": "3 Days",
    "appliedOn": "2026-02-15 00:00:00",
    "leaveDates": "Jun 29 2026 - Jul 01 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Aarav Nair",
    "mediamintId": "MM2851",
    "email": "aarav.nair@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "RH",
    "daysHours": "1 Day",
    "appliedOn": "2026-04-05 00:00:00",
    "leaveDates": "Jun 29 2026",
    "reason": "Festival holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "Philippines"
  },
  {
    "employeeName": "Riya Iyer",
    "mediamintId": "MM2472",
    "email": "riya.iyer@mediamint.com",
    "managerName": "Suresh Babu",
    "leaveType": "SL",
    "daysHours": "1 Day",
    "appliedOn": "2026-03-13 00:00:00",
    "leaveDates": "Jul 20 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Arjun Das",
    "mediamintId": "MM3960",
    "email": "arjun.das@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "ML",
    "daysHours": "2 Days",
    "appliedOn": "2026-05-30 00:00:00",
    "leaveDates": "Jul 23 2026 - Jul 25 2026",
    "reason": "Maternity leave",
    "day": "Full",
    "startDate": "Jul 23 2026",
    "endDate": "Jul 25 2026",
    "status": "Approved",
    "country": "United States"
  },
  {
    "employeeName": "Aditya Ghosh",
    "mediamintId": "MM2110",
    "email": "aditya.ghosh@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "CL",
    "daysHours": "1 Day",
    "appliedOn": "2026-04-25 00:00:00",
    "leaveDates": "Jun 25 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected",
    "country": "India"
  },
  {
    "employeeName": "Kavya Menon",
    "mediamintId": "MM4181",
    "email": "kavya.menon@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "CL",
    "daysHours": "3 Days",
    "appliedOn": "2026-03-04 00:00:00",
    "leaveDates": "Jul 11 2026 - Jul 13 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Pooja Menon",
    "mediamintId": "MM2818",
    "email": "pooja.menon@mediamint.com",
    "managerName": "Pradeep Gaddamedi",
    "leaveType": "CL",
    "daysHours": "1 Day",
    "appliedOn": "2026-03-06 00:00:00",
    "leaveDates": "Jul 12 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "United States"
  },
  {
    "employeeName": "Kabir Bhat",
    "mediamintId": "MM3410",
    "email": "kabir.bhat@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "SL",
    "daysHours": "0.5 Day",
    "appliedOn": "2026-04-12 00:00:00",
    "leaveDates": "Jul 13 2026",
    "reason": "Not feeling well",
    "day": "Half",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "United States"
  },
  {
    "employeeName": "Arjun Rao",
    "mediamintId": "MM3976",
    "email": "arjun.rao@mediamint.com",
    "managerName": "Suresh Babu",
    "leaveType": "RH",
    "daysHours": "1 Day",
    "appliedOn": "2026-07-10 00:00:00",
    "leaveDates": "Jul 20 2026",
    "reason": "Festival holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn",
    "country": "India"
  },
  {
    "employeeName": "Ananya Mehta",
    "mediamintId": "MM4914",
    "email": "ananya.mehta@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "WFH",
    "daysHours": "1 Day",
    "appliedOn": "2026-05-20 00:00:00",
    "leaveDates": "Jul 20 2026",
    "reason": "Working from home",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending",
    "country": "India"
  },
  {
    "employeeName": "Sneha Mehta",
    "mediamintId": "MM3897",
    "email": "sneha.mehta@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "SL",
    "daysHours": "0.5 Day",
    "appliedOn": "2026-06-19 00:00:00",
    "leaveDates": "Jun 30 2026",
    "reason": "Not feeling well",
    "day": "Half",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Aryan Verma",
    "mediamintId": "MM4686",
    "email": "aryan.verma@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "PTO",
    "daysHours": "1 Day",
    "appliedOn": "2026-03-11 00:00:00",
    "leaveDates": "Jul 12 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected",
    "country": "United States"
  },
  {
    "employeeName": "Aarav Sharma",
    "mediamintId": "MM4975",
    "email": "aarav.sharma@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "RH",
    "daysHours": "1 Day",
    "appliedOn": "2026-06-14 00:00:00",
    "leaveDates": "Jul 23 2026",
    "reason": "Festival holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Pending",
    "country": "India"
  },
  {
    "employeeName": "Aarav Das",
    "mediamintId": "MM2871",
    "email": "aarav.das@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "OT",
    "daysHours": "8 Hours",
    "appliedOn": "2026-03-04 00:00:00",
    "leaveDates": "Jul 05 2026",
    "reason": "Worked on a mandatory holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "United States"
  },
  {
    "employeeName": "Varun Patel",
    "mediamintId": "MM2249",
    "email": "varun.patel@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "WFH",
    "daysHours": "3 Days",
    "appliedOn": "2026-04-11 00:00:00",
    "leaveDates": "Jul 19 2026 - Jul 21 2026",
    "reason": "Working from home",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected",
    "country": "India"
  },
  {
    "employeeName": "Aditya Ghosh",
    "mediamintId": "MM2621",
    "email": "aditya.ghosh@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "CL",
    "daysHours": "1 Day",
    "appliedOn": "2026-03-02 00:00:00",
    "leaveDates": "Jun 21 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected",
    "country": "India"
  },
  {
    "employeeName": "Ishita Patel",
    "mediamintId": "MM3939",
    "email": "ishita.patel@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "RH",
    "daysHours": "1 Day",
    "appliedOn": "2026-06-10 00:00:00",
    "leaveDates": "Jul 25 2026",
    "reason": "Festival holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "United States"
  },
  {
    "employeeName": "Neha Joshi",
    "mediamintId": "MM2434",
    "email": "neha.joshi@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "CL",
    "daysHours": "0.5 Day",
    "appliedOn": "2026-06-26 00:00:00",
    "leaveDates": "Jul 05 2026",
    "reason": "Personal work",
    "day": "Half",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "United States"
  },
  {
    "employeeName": "Neha Sharma",
    "mediamintId": "MM2259",
    "email": "neha.sharma@mediamint.com",
    "managerName": "Suresh Babu",
    "leaveType": "SL",
    "daysHours": "3 Days",
    "appliedOn": "2026-04-18 00:00:00",
    "leaveDates": "Jul 29 2026 - Jul 31 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Rejected",
    "country": "India"
  },
  {
    "employeeName": "Rohan Verma",
    "mediamintId": "MM4081",
    "email": "rohan.verma@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "CL",
    "daysHours": "3 Days",
    "appliedOn": "2026-03-10 00:00:00",
    "leaveDates": "Jul 22 2026 - Jul 24 2026",
    "reason": "Personal work",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "United States"
  },
  {
    "employeeName": "Varun Verma",
    "mediamintId": "MM2561",
    "email": "varun.verma@mediamint.com",
    "managerName": "Rangarajan Murugesan",
    "leaveType": "SL",
    "daysHours": "1 Day",
    "appliedOn": "2026-06-09 00:00:00",
    "leaveDates": "Jul 15 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn",
    "country": "India"
  },
  {
    "employeeName": "Vivaan Rao",
    "mediamintId": "MM4742",
    "email": "vivaan.rao@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "OT",
    "daysHours": "8 Hours",
    "appliedOn": "2026-06-09 00:00:00",
    "leaveDates": "Jun 29 2026",
    "reason": "Worked on a mandatory holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Nikhil Menon",
    "mediamintId": "MM2385",
    "email": "nikhil.menon@mediamint.com",
    "managerName": "Anita Krishnan",
    "leaveType": "SL",
    "daysHours": "1 Day",
    "appliedOn": "2026-03-08 00:00:00",
    "leaveDates": "Jun 30 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Dev Bose",
    "mediamintId": "MM3725",
    "email": "dev.bose@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "PTO",
    "daysHours": "1 Day",
    "appliedOn": "2026-04-10 00:00:00",
    "leaveDates": "Jul 10 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn",
    "country": "India"
  },
  {
    "employeeName": "Arjun Ghosh",
    "mediamintId": "MM3878",
    "email": "arjun.ghosh@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "SL",
    "daysHours": "3 Days",
    "appliedOn": "2026-07-06 00:00:00",
    "leaveDates": "Jul 14 2026 - Jul 16 2026",
    "reason": "Not feeling well",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "United States"
  },
  {
    "employeeName": "Ananya Menon",
    "mediamintId": "MM2429",
    "email": "ananya.menon@mediamint.com",
    "managerName": "Moumita Haldi",
    "leaveType": "PTO",
    "daysHours": "1 Day",
    "appliedOn": "2026-05-04 00:00:00",
    "leaveDates": "Jul 07 2026",
    "reason": "Planned vacation",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Approved",
    "country": "India"
  },
  {
    "employeeName": "Varun Pillai",
    "mediamintId": "MM4768",
    "email": "varun.pillai@mediamint.com",
    "managerName": "Keerthi J",
    "leaveType": "OT",
    "daysHours": "8 Hours",
    "appliedOn": "2026-03-29 00:00:00",
    "leaveDates": "Jun 29 2026",
    "reason": "Worked on a mandatory holiday",
    "day": "Full",
    "startDate": "NA",
    "endDate": "NA",
    "status": "Withdrawn",
    "country": "India"
  }
];
